# Generated by Django 4.0.1 on 2022-01-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='poster',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
